services:
  client:
    build: ./cliente
    container_name: client-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cliente:/app  
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host  

  server:
    build: ./servidor
    container_name: server-app
    ports:
      - "6000:6000"
    network_mode: host 