services:
  client:
    build: ./cliente
    container_name: client-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cliente:/app
      - ./protocolo:/protocolo
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    depends_on:
      - banco
      - server


  server:
    build: ./servidor
    container_name: server-app
    volumes:
      - ./servidor:/app
      - ./protocolo:/protocolo
    ports:
      - "6000:6000"
    network_mode: host
    depends_on:
      - banco

  banco:
    build: ./banco
    container_name: database-app
    volumes:
      - ./banco:/app
      - ./protocolo:/protocolo
    ports:
      - "3600:3600"
    network_mode: host
